name: iman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: null
  http: ^1.2.0
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  flutter_compass: ^0.8.0
  vector_math: ^2.1.4

  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
